version: "3"
services:
  client:
    build:
      context: client
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
  api:
    build:
      context: server
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
      - redis
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app
    environment:
      - API_PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=postgres_password
      - PG_PORT=5432
  worker:
    build:
      context: worker
      dockerfile: Dockerfile.dev
    depends_on:
      - redis
    volumes:
      - /usr/app/node_modules
      - ./worker:/usr/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  postgres:
    image: "postgres:latest"
  redis:
    image: "redis:latest"
  nginx:
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - api
      - client
    ports:
      - "3050:80"
